export const envs = {
  BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
  SECRECT_KEY_SIGNUP_TOKEN: String(process.env.NEXT_PUBLIC_SECRECT_KEY_SIGNUP_TOKEN),
  SERVER_GRAPHQL: String(process.env.NEXT_PUBLIC_SERVER_GRAPHQL),
};
